export enum vreugde {
    "GELUKKIG-JOY",
    "ENTHOUSIAST-ENTHOUSIAST",
    "TEVREDEN-SATISFIED",
    "VERLIEFD-IN LOVE",
    "BLIJ-GLAD",
    "ZELFVERZEKERD-CONFIDENT",
    "ONTSPANNEN-RELAXED"

}

export enum verdriet {
    "ZWAARMOEDIG-MELANCHOLIC",
    "ZELFMEDELIJDEN-SELF PITTY",
    "BEDROEFD-SAD",
    "WANHOPIG-DISPAIR",
    "EENZAM-LONELY",
    "DEPRESSIEF-DEPRESSIVE",
    "ROUWEND-GRIEF" 
}

export enum angst {
    "RUSTELOOS-RESTLESS",
    "FOBISCH-SCARED",
    "PANIEKERIG-PANIC",
    "ZENUWACHTIG-NERVOUS",
    "ONGERUST-WORRIED",
    "BEZORGD-CONCERNED",
    "WANTROUWEND-SUSPICIOUS"
}

export enum boos {
    "VERBOLGEN-ANGRY",
    "ERGEREN-ANNOY",
    "VERBITTERD-BITTER",
    "GEIRRITEERD-IRRITATED",
    "VIJANDIG-HOSTILE",
    "FURIEUS-FURIOUS",
    "VERONTWAARDIGD-OUTRAGED"


}

export enum verrassing {
    "GECHIQUEERD-CHEATED",
    "VERBIJSTERD-BAFFLED",
    "VERWONDERD-AMAZED" ,
    "OVERROMPELD-SUPRISED",
    "ONTSTELT-UPSET",

}

export enum afschuw {
    "MINACHTEND-DESPICABLE",
    "AVERSIE-DISLIKE",
    "WEERZIN-DISGUST",
    "ONTZET-HORRIEFIED",

}